name: push

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.0.x
      - uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{runner.os}}-nuget
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test -c Release --no-build --logger trx --results-directory "TestResults"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results
          path: TestResults
        if: ${{ always() }}
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_os: ["linux-x64"]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.0.x
      - uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{runner.os}}-nuget
      - name: Pack
        working-directory: src
        run: |
          dotnet publish \
            /p:CI_COMMIT_REF_NAME="${{ github.ref_name }}" \
            /p:CI_COMMIT_SHORT_SHA="${{ steps.short-sha.outputs.sha }}" \
            /p:CI_COMMIT_SHA="${{ github.sha }}" \
            /p:CI_REPOSITORY_URL="${{ github.event.repository.clone_url }}" \
            /p:CI_PROJECT_URL="${{ github.event.repository.html_url }}" \
            /p:VersionSuffix="${{github.run_id}}" \
            -c Release -r ${{matrix.target_os}} -o ./src/ArkProjects.UefiModTools/bin/publish ArkProjects.UefiModTools
      - name: Dist
        uses: actions/upload-artifact@v4
        with:
          name: uefi-mod-tools_${{matrix.target_os}}_prebuild
          path: ./src/ArkProjects.UefiModTools/bin/publish
